### ISSUE TITLE
@ManyToMany

### ISSUE THREAD

**Issue by ber01** [ber01/One-Click-Reviewer#5]
연결 테이블을 자동으로 처리하여준다.

장점
- 도메인이 단순해진다.

단점
- 연결 테이블에 추가적인 컬럼이 필요하면 문제가 발생한다.

현재 프로젝트에서 유저_장르 `Account_Genre` 도메인을 만들어서 관리할 필요가 있을까?

**Comment by mkshin96** [comment]
프로젝트의 구조(엔티티 간의 관계 등)를 좀 더 명확히 하기 위해서는 중간 테이블을 명시하는 것이 좋아보임

아래 블로그를 참고하면 좋을 듯 함
https://ict-nroo.tistory.com/127

**Comment by ber01** [comment]
`Account_Genre` 테이블의 도메인 `MyGenre` 를 만들어보니 저장을 할 때 `MyGenre` 객체를 생성하고 저장해야 하는 단계가 늘어났음
엔티티의 관계가 명확해진다는 장점은 있지만 중간 테이블에 추가될 내용이 없으면 굳이 이렇게 관리하는 것이 좋을까에 대한 의문이 생겨남

**Comment by ber01** [comment]
연결 엔티티 `MyGenre` 의 기본키
- `ACCOUNT_ID` 와 `GENRE_ID` 의 복합키를 사용하는 방법
- 데이터베이스에서 자동으로 생성하는 대리 키를 사용하는 방법

전자는 식별자 클래스가 필요하고, 하나의 기본 키를 사용하는 방법에 비하여 `ORM` 매핑에 처리할 일이 많다.
후자는 데이터베이스에 불필요한 데이터 (자동으로 생성하는 대리 키)가 삽입된다.

후자가 사용하기 간편하고 이해하기 쉬웠기에 후자를 선택
그런데 `@ManyToMany` 를 사용하면 전자 방식으로 테이블이 만들어짐

**Comment by ber01** [comment]
> `Account_Genre` 테이블의 도메인 `MyGenre` 를 만들어보니 저장을 할 때 `MyGenre` 객체를 생성하고 저장해야 하는 단계가 늘어났음
> 엔티티의 관계가 명확해진다는 장점은 있지만 중간 테이블에 추가될 내용이 없으면 굳이 이렇게 관리하는 것이 좋을까에 대한 의문이 생겨남

혹시나 하는 확장 가능성도 있고 공부 목적으로 연결 엔티티를 사용하기로 결정
